# This Docker Compose file is to use for CI purposes only
# At Lago we use it to run ours integrations tests

version: '3.8'

networks:
  default:
    name: lago-ci

services:
  front:
    image: getlago/front:ci
    container_name: lago-front
    restart: unless-stopped
    environment:
      API_URL: http://localhost:3000
      NODE_ENV: staging
    ports:
      - 80:80
    networks:
      - lago-ci
