// For future me, fixture like that are terrible, I know.
// We should have an other system for that, but I don't have time for that right now.
import { InvoiceTypeEnum } from '~/generated/graphql'

export const INVOICE_FIXTURE_ID = '1234'

export const fourOFourInvoiceMock = () => ({
  mock: {
    invoice: {
      id: INVOICE_FIXTURE_ID,
      refundableAmountCents: '0',
      creditableAmountCents: '0',
      invoiceType: InvoiceTypeEnum.Subscription,
      fees: [],
      invoiceSubscriptions: [],
      currency: 'EUR',
      number: 'HOO-AFA3-004-002',
      paymentStatus: 'pending',
      subTotalIncludingTaxesAmountCents: '0',
      couponsAmountCents: '0',
      feesAmountCents: '0',
      versionNumber: 3,
      __typename: 'Invoice',
    },
  },
})

export const fullSubscriptionInvoiceMockAndExpect = () => ({
  mock: {
    invoice: {
      id: INVOICE_FIXTURE_ID,
      refundableAmountCents: '0',
      creditableAmountCents: '2700000',
      invoiceType: InvoiceTypeEnum.Subscription,
      fees: [
        {
          id: 'fee-1-id',
          amountCurrency: 'EUR',
          itemCode: 'standard_plan',
          itemName: 'Standard Plan',
          invoiceName: 'Invoice custom name',
          creditableAmountCents: '100',
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
        {
          id: 'fee-2-id',
          amountCurrency: 'EUR',
          itemCode: 'sum_bm',
          itemName: 'Sum BM',
          invoiceName: 'Invoice custom name',
          creditableAmountCents: '2699900',
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
      ],
      invoiceSubscriptions: [
        {
          subscription: {
            id: 'invoice-subscription-subscription-1-id',
            name: null,
            plan: {
              id: 'invoice-subscription-subscription-1-plan-id',
              name: 'Standard Plan',
              invoiceDisplayName: 'Standard plan',
              __typename: 'Plan',
            },
            __typename: 'Subscription',
          },
          fees: [
            {
              id: 'invoice-subscription-fee-1-id',
              amountCurrency: 'EUR',
              feeType: 'subscription',
              appliedTaxes: [],
              invoiceName: 'Invoice custom name',
              groupName: 'group 1 custom name',
              creditableAmountCents: '100',
              trueUpFee: null,
              charge: null,
              group: null,
              __typename: 'Fee',
            },
            {
              id: 'invoice-subscription-fee-2-id',
              amountCurrency: 'EUR',
              feeType: 'charge',
              appliedTaxes: [],
              invoiceName: 'Invoice custom name',
              groupName: 'group 1 custom name',
              creditableAmountCents: '2699900',
              trueUpFee: null,
              charge: {
                id: 'invoice-subscription-fee-2-charge-id',
                billableMetric: {
                  id: 'invoice-subscription-fee-2-charge-bm-id',
                  name: 'Sum BM',
                  __typename: 'BillableMetric',
                },
                __typename: 'Charge',
              },
              group: null,
              __typename: 'Fee',
            },
          ],
          __typename: 'InvoiceSubscription',
        },
      ],
      currency: 'EUR',
      number: 'HOO-AFA3-004-002',
      paymentStatus: 'pending',
      subTotalIncludingTaxesAmountCents: '2700100',
      couponsAmountCents: '0',
      feesAmountCents: '2700100',
      versionNumber: 3,
      __typename: 'Invoice',
    },
  },
  transformedObject: {},
})

export const fullSubscriptionInvoiceGroupTrueUpMockAndExpect = () => ({
  mock: {
    invoice: {
      id: INVOICE_FIXTURE_ID,
      refundableAmountCents: '0',
      creditableAmountCents: '62833',
      invoiceType: InvoiceTypeEnum.Subscription,
      fees: [
        {
          id: 'b7e53061-73b5-46bf-8f1a-2f49d50c672c',
          amountCurrency: 'EUR',
          itemCode: 'group_true_up',
          itemName: 'group true up',
          creditableAmountCents: '167',
          invoiceName: 'Invoice custom name',
          groupName: null,
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
        {
          id: 'e94a7773-7641-4d81-a869-bb5c021c2817',
          amountCurrency: 'EUR',
          itemCode: 'count_bm_two_dimensions',
          itemName: 'Count BM - Two dimensions',
          creditableAmountCents: '3000',
          invoiceName: 'Invoice custom name',
          groupName: null,
          appliedTaxes: [],
          trueUpFee: {
            id: 'af3ca6df-02ba-4442-a455-c7eb6b0edc6b',
            __typename: 'Fee',
          },
          __typename: 'Fee',
        },
        {
          id: 'df9b74ff-b050-44a5-aad4-3ec87999f3c6',
          amountCurrency: 'EUR',
          itemCode: 'count_bm_two_dimensions',
          itemName: 'Count BM - Two dimensions',
          creditableAmountCents: '2000',
          invoiceName: 'Invoice custom name',
          groupName: null,
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
        {
          id: '0e1bd51c-07fe-445b-aade-28fdc88a488c',
          amountCurrency: 'EUR',
          itemCode: 'count_bm_two_dimensions',
          itemName: 'Count BM - Two dimensions',
          creditableAmountCents: '1000',
          invoiceName: 'Invoice custom name',
          groupName: null,
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
        {
          id: 'af3ca6df-02ba-4442-a455-c7eb6b0edc6b',
          amountCurrency: 'EUR',
          itemCode: 'count_bm_two_dimensions',
          itemName: 'Count BM - Two dimensions',
          creditableAmountCents: '10666',
          invoiceName: 'Invoice custom name',
          groupName: null,
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
        {
          id: '58b6e874-7d5f-4871-a9b3-7379dfbfd787',
          amountCurrency: 'EUR',
          itemCode: 'count_bm_one_dimension',
          itemName: 'Count BM - One dimension',
          creditableAmountCents: '3000',
          invoiceName: 'Invoice custom name',
          groupName: null,
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
        {
          id: '0769b8c4-38ed-4248-bda9-d62218c91b37',
          amountCurrency: 'EUR',
          itemCode: 'count_bm_one_dimension',
          itemName: 'Count BM - One dimension',
          creditableAmountCents: '3000',
          invoiceName: 'Invoice custom name',
          groupName: null,
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
        {
          id: '18892329-3951-4134-ac57-fe7233b1c723',
          amountCurrency: 'EUR',
          itemCode: 'sum_bm',
          itemName: 'Sum BM',
          creditableAmountCents: '40000',
          invoiceName: 'Invoice custom name',
          groupName: null,
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
        {
          id: '18892321-3951-4114-ac17-fe723311c723',
          amountCurrency: 'EUR',
          itemCode: 'sum_bm',
          itemName: 'Sum BM',
          creditableAmountCents: '0',
          invoiceName: 'Invoice custom name',
          groupName: null,
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
      ],
      invoiceSubscriptions: [
        {
          subscription: {
            id: 'b76a0e8c-26c5-4a04-9fe0-f928f0db1c5a',
            name: '',
            plan: {
              id: '3a16e062-7c1a-42b8-ba38-02fa11b1279d',
              name: 'group true up',
              invoiceDisplayName: 'Standard Plan',
              __typename: 'Plan',
            },
            __typename: 'Subscription',
          },
          fees: [
            {
              id: 'b7e53061-73b5-46bf-8f1a-2f49d50c672c',
              amountCurrency: 'EUR',
              feeType: 'subscription',
              appliedTaxes: [],
              creditableAmountCents: '167',
              invoiceName: 'Invoice custom name',
              groupName: null,
              trueUpFee: null,
              charge: null,
              group: null,
              __typename: 'Fee',
            },
            {
              id: 'e94a7773-7641-4d81-a869-bb5c021c2817',
              amountCurrency: 'EUR',
              feeType: 'charge',
              appliedTaxes: [],
              creditableAmountCents: '3000',
              invoiceName: 'Invoice custom name',
              groupName: null,
              trueUpFee: {
                id: 'af3ca6df-02ba-4442-a455-c7eb6b0edc6b',
                __typename: 'Fee',
              },
              charge: {
                id: '5ff24500-2c67-4872-9808-746c59e94d38',
                billableMetric: {
                  id: '3e99dae9-46dc-4020-a676-3fc5020c22f9',
                  name: 'Count BM - Two dimensions',
                  __typename: 'BillableMetric',
                },
                __typename: 'Charge',
              },
              group: {
                key: 'AWS',
                value: 'europe',
                __typename: 'Group',
              },
              __typename: 'Fee',
            },
            {
              id: 'df9b74ff-b050-44a5-aad4-3ec87999f3c6',
              amountCurrency: 'EUR',
              feeType: 'charge',
              appliedTaxes: [],
              creditableAmountCents: '2000',
              invoiceName: 'Invoice custom name',
              groupName: null,
              trueUpFee: null,
              charge: {
                id: '5ff24500-2c67-4872-9808-746c59e94d38',
                billableMetric: {
                  id: '3e99dae9-46dc-4020-a676-3fc5020c22f9',
                  name: 'Count BM - Two dimensions',
                  __typename: 'BillableMetric',
                },
                __typename: 'Charge',
              },
              group: {
                key: 'AWS',
                value: 'usa',
                __typename: 'Group',
              },
              __typename: 'Fee',
            },
            {
              id: '0e1bd51c-07fe-445b-aade-28fdc88a488c',
              amountCurrency: 'EUR',
              feeType: 'charge',
              appliedTaxes: [],
              creditableAmountCents: '1000',
              invoiceName: 'Invoice custom name',
              groupName: null,
              trueUpFee: null,
              charge: {
                id: '5ff24500-2c67-4872-9808-746c59e94d38',
                billableMetric: {
                  id: '3e99dae9-46dc-4020-a676-3fc5020c22f9',
                  name: 'Count BM - Two dimensions',
                  __typename: 'BillableMetric',
                },
                __typename: 'Charge',
              },
              group: {
                key: 'Google',
                value: 'usa',
                __typename: 'Group',
              },
              __typename: 'Fee',
            },
            {
              id: 'af3ca6df-02ba-4442-a455-c7eb6b0edc6b',
              amountCurrency: 'EUR',
              feeType: 'charge',
              appliedTaxes: [],
              creditableAmountCents: '10666',
              invoiceName: 'Invoice custom name',
              groupName: null,
              trueUpFee: null,
              charge: {
                id: '5ff24500-2c67-4872-9808-746c59e94d38',
                billableMetric: {
                  id: '3e99dae9-46dc-4020-a676-3fc5020c22f9',
                  name: 'Count BM - Two dimensions',
                  __typename: 'BillableMetric',
                },
                __typename: 'Charge',
              },
              group: null,
              __typename: 'Fee',
            },
            {
              id: '58b6e874-7d5f-4871-a9b3-7379dfbfd787',
              amountCurrency: 'EUR',
              feeType: 'charge',
              appliedTaxes: [],
              creditableAmountCents: '3000',
              invoiceName: 'Invoice custom name',
              groupName: null,
              trueUpFee: null,
              charge: {
                id: '594fe1d1-69f1-4b47-8cae-9c76fd409f76',
                billableMetric: {
                  id: '6576c6f2-947e-496c-ac5b-19b781ad0046',
                  name: 'Count BM - One dimension',
                  __typename: 'BillableMetric',
                },
                __typename: 'Charge',
              },
              group: {
                key: null,
                value: 'france',
                __typename: 'Group',
              },
              __typename: 'Fee',
            },
            {
              id: '0769b8c4-38ed-4248-bda9-d62218c91b37',
              amountCurrency: 'EUR',
              feeType: 'charge',
              appliedTaxes: [],
              creditableAmountCents: '3000',
              invoiceName: 'Invoice custom name',
              groupName: null,
              trueUpFee: null,
              charge: {
                id: '594fe1d1-69f1-4b47-8cae-9c76fd409f76',
                billableMetric: {
                  id: '6576c6f2-947e-496c-ac5b-19b781ad0046',
                  name: 'Count BM - One dimension',
                  __typename: 'BillableMetric',
                },
                __typename: 'Charge',
              },
              group: {
                key: null,
                value: 'italy',
                __typename: 'Group',
              },
              __typename: 'Fee',
            },
            {
              id: '18892329-3951-4134-ac57-fe7233b1c723',
              amountCurrency: 'EUR',
              feeType: 'charge',
              appliedTaxes: [],
              creditableAmountCents: '40000',
              invoiceName: 'Invoice custom name',
              groupName: null,
              trueUpFee: null,
              charge: {
                id: '2030bb05-e627-40a5-b420-538fb6fbecab',
                billableMetric: {
                  id: '67774fc5-62e0-40c3-9502-ac7a2799e71d',
                  name: 'Sum BM',
                  __typename: 'BillableMetric',
                },
                __typename: 'Charge',
              },
              group: null,
              __typename: 'Fee',
            },
            {
              id: '18892321-3951-4114-ac17-fe723311c723',
              amountCurrency: 'EUR',
              feeType: 'charge',
              appliedTaxes: [],
              creditableAmountCents: '0',
              invoiceName: 'Invoice custom name',
              groupName: null,
              trueUpFee: null,
              charge: {
                id: '2030bb05-e627-40a5-b420-538fb6fbecac',
                billableMetric: {
                  id: '67774fc5-62e0-40c3-9502-ac7a2799e71d',
                  name: 'Sum BM',
                  __typename: 'BillableMetric',
                },
                __typename: 'Charge',
              },
              group: null,
              __typename: 'Fee',
            },
          ],
          __typename: 'InvoiceSubscription',
        },
      ],
      currency: 'EUR',
      number: 'HOO-AFA3-006-036',
      paymentStatus: 'pending',
      subTotalIncludingTaxesAmountCents: '62833',
      couponsAmountCents: '0',
      feesAmountCents: '62833',
      versionNumber: 3,
      __typename: 'Invoice',
    },
  },
  transformedObject: {
    'b76a0e8c-26c5-4a04-9fe0-f928f0db1c5a': {
      fees: {
        '0_b7e53061-73b5-46bf-8f1a-2f49d50c672c': {
          appliedTaxes: [],
          checked: true,
          id: 'b7e53061-73b5-46bf-8f1a-2f49d50c672c',
          isTrueUpFee: false,
          maxAmount: '167',
          name: 'Invoice custom name',
          trueUpFee: null,
          value: 1.67,
        },
        '2_af3ca6df-02ba-4442-a455-c7eb6b0edc6b': {
          appliedTaxes: [],
          checked: true,
          id: 'af3ca6df-02ba-4442-a455-c7eb6b0edc6b',
          isTrueUpFee: true,
          maxAmount: '10666',
          name: 'Invoice custom name',
          trueUpFee: null,
          value: 106.66,
        },
        '4_18892329-3951-4134-ac57-fe7233b1c723': {
          appliedTaxes: [],
          checked: true,
          id: '18892329-3951-4134-ac57-fe7233b1c723',
          isTrueUpFee: false,
          maxAmount: '40000',
          name: 'Invoice custom name',
          trueUpFee: null,
          value: 400,
        },
        '594fe1d1-69f1-4b47-8cae-9c76fd409f76': {
          grouped: {
            '0769b8c4-38ed-4248-bda9-d62218c91b37': {
              appliedTaxes: [],
              checked: true,
              id: '0769b8c4-38ed-4248-bda9-d62218c91b37',
              maxAmount: '3000',
              name: 'italy',
              value: 30,
            },
            '58b6e874-7d5f-4871-a9b3-7379dfbfd787': {
              appliedTaxes: [],
              checked: true,
              id: '58b6e874-7d5f-4871-a9b3-7379dfbfd787',
              maxAmount: '3000',
              name: 'france',
              value: 30,
            },
          },
          name: 'Invoice custom name',
        },
        '5ff24500-2c67-4872-9808-746c59e94d38': {
          grouped: {
            '0e1bd51c-07fe-445b-aade-28fdc88a488c': {
              appliedTaxes: [],
              checked: true,
              id: '0e1bd51c-07fe-445b-aade-28fdc88a488c',
              maxAmount: '1000',
              name: 'Google • usa',
              value: 10,
            },
            'df9b74ff-b050-44a5-aad4-3ec87999f3c6': {
              appliedTaxes: [],
              checked: true,
              id: 'df9b74ff-b050-44a5-aad4-3ec87999f3c6',
              maxAmount: '2000',
              name: 'AWS • usa',
              value: 20,
            },
            'e94a7773-7641-4d81-a869-bb5c021c2817': {
              appliedTaxes: [],
              checked: true,
              id: 'e94a7773-7641-4d81-a869-bb5c021c2817',
              maxAmount: '3000',
              name: 'AWS • europe',
              value: 30,
            },
          },
          name: 'Invoice custom name',
        },
      },
      subscriptionName: 'Standard Plan',
    },
  },
})

export const fullOneOffInvoiceMockAndExpect = () => ({
  mock: {
    invoice: {
      id: INVOICE_FIXTURE_ID,
      refundableAmountCents: '0',
      creditableAmountCents: '2700000',
      invoiceType: InvoiceTypeEnum.OneOff,
      fees: [
        {
          id: 'fee-1-id',
          amountCurrency: 'EUR',
          itemCode: 'standard_plan',
          itemName: 'Standard Plan',
          creditableAmountCents: '100',
          invoiceName: 'Invoice custom name',
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
        {
          id: 'fee-2-id',
          amountCurrency: 'EUR',
          itemCode: 'sum_bm',
          itemName: 'Sum BM',
          creditableAmountCents: '0',
          invoiceName: 'Invoice custom name',
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
        {
          id: 'fee-3-id',
          amountCurrency: 'EUR',
          itemCode: 'sum_bm',
          itemName: 'Sum BM',
          creditableAmountCents: '2699900',
          invoiceName: 'Invoice custom name',
          appliedTaxes: [],
          trueUpFee: null,
          __typename: 'Fee',
        },
      ],
      invoiceSubscriptions: [],
      currency: 'EUR',
      number: 'HOO-AFA3-004-002',
      paymentStatus: 'pending',
      subTotalIncludingTaxesAmountCents: '2700100',
      couponsAmountCents: '0',
      feesAmountCents: '2700100',
      versionNumber: 3,
      __typename: 'Invoice',
    },
  },
  transformedObject: [
    {
      appliedTaxes: [],
      checked: true,
      id: 'fee-1-id',
      maxAmount: '100',
      name: 'Invoice custom name',
      value: 1,
    },
    {
      appliedTaxes: [],
      checked: true,
      id: 'fee-3-id',
      maxAmount: '2699900',
      name: 'Invoice custom name',
      value: 26999,
    },
  ],
})
