const colorVariables = [
  '--v2-white',
  '--v2-alpha-black-04',
  '--v2-alpha-black-08',
  '--v2-alpha-black-40',
  '--v2-alpha-black-64',
  '--v2-alpha-white-06',
  '--v2-alpha-white-10',
  '--v2-alpha-white-12',
  '--v2-amber-50',
  '--v2-amber-100',
  '--v2-amber-200',
  '--v2-amber-300',
  '--v2-amber-400',
  '--v2-amber-500',
  '--v2-amber-600',
  '--v2-amber-700',
  '--v2-amber-800',
  '--v2-amber-900',
  '--v2-amber-950',
  '--v2-brand-50',
  '--v2-brand-100',
  '--v2-brand-200',
  '--v2-brand-300',
  '--v2-brand-400',
  '--v2-brand-500',
  '--v2-brand-600',
  '--v2-brand-700',
  '--v2-brand-800',
  '--v2-brand-900',
  '--v2-brand-950',
  '--v2-green-50',
  '--v2-green-100',
  '--v2-green-200',
  '--v2-green-300',
  '--v2-green-400',
  '--v2-green-500',
  '--v2-green-600',
  '--v2-green-700',
  '--v2-green-800',
  '--v2-green-900',
  '--v2-green-950',
  '--v2-neutral-50',
  '--v2-neutral-100',
  '--v2-neutral-200',
  '--v2-neutral-300',
  '--v2-neutral-400',
  '--v2-neutral-500',
  '--v2-neutral-600',
  '--v2-neutral-700',
  '--v2-neutral-750',
  '--v2-neutral-800',
  '--v2-neutral-850',
  '--v2-neutral-900',
  '--v2-neutral-950',
  '--v2-red-50',
  '--v2-red-100',
  '--v2-red-200',
  '--v2-red-300',
  '--v2-red-400',
  '--v2-red-500',
  '--v2-red-600',
  '--v2-red-700',
  '--v2-red-800',
  '--v2-red-900',
  '--v2-red-950',
  '--v2-violet-50',
  '--v2-violet-100',
  '--v2-violet-200',
  '--v2-violet-300',
  '--v2-violet-400',
  '--v2-violet-500',
  '--v2-violet-600',
  '--v2-violet-700',
  '--v2-violet-800',
  '--v2-violet-900',
  '--v2-violet-950',
  '--color-canvas',
  '--color-surface',
  '--color-surface-raised',
  '--color-surface-inset',
  '--color-text-default',
  '--color-text-muted',
  '--color-text-subtle',
  '--color-border-subtle',
  '--color-border-default',
  '--color-border-strong',
  '--color-action-primary',
  '--color-action-primary-hover',
  '--color-action-primary-pressed',
  '--color-action-primary-foreground',
  '--color-interactive-hover',
  '--color-interactive-pressed',
  '--color-selected',
  '--color-selected-foreground',
  '--color-link',
  '--color-link-hover',
  '--color-focus-ring',
  '--color-focus-border',
  '--color-disabled',
  '--color-disabled-foreground',
  '--color-disabled-border',
  '--color-info',
  '--color-info-foreground',
  '--color-info-border',
  '--color-success',
  '--color-success-foreground',
  '--color-success-border',
  '--color-warning',
  '--color-warning-foreground',
  '--color-warning-border',
  '--color-danger',
  '--color-danger-foreground',
  '--color-danger-border',
  '--color-destructive',
  '--color-destructive-hover',
  '--color-destructive-pressed',
  '--color-destructive-foreground',
  '--color-overlay',
  '--color-inverse',
  '--color-inverse-foreground',
  '--color-icon-default',
  '--color-icon-muted',
  '--color-icon-subtle',
]

type TailwindColor = (options: { opacityValue?: string; opacityVariable?: string }) => string

export const v2TailwindColors: Record<string, TailwindColor> = Object.fromEntries(
  colorVariables.map((variable) => [
    variable.replace(/^--(?:color-)?/, ''),
    ({ opacityValue, opacityVariable }: Parameters<TailwindColor>[0]): string => {
      const color = `var(${variable})`

      // Tailwind supplies an opacity variable even for classes without a slash modifier.
      if (opacityValue === undefined || opacityVariable !== undefined) return color

      return `color-mix(in srgb, ${color} calc(${opacityValue} * 100%), transparent)`
    },
  ]),
)
