import { createContext, ReactNode, useContext, useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { usePanel, UsePanelReturn } from '~/hooks/ui/usePanel'
import { useCurrentUser } from '~/hooks/useCurrentUser'

const DeveloperToolContext = createContext<DeveloperToolContextType | undefined>(undefined)

export const DEVTOOL_TAB_PARAMS = 'devtool-tab'
export const DEVTOOL_AUTO_SAVE_ID = 'devtools'
// This is generated by the react-resizable-panels library and is used to save the state of the devtools
export const DEVTOOL_AUTO_SAVE_KEY = `react-resizable-panels:${DEVTOOL_AUTO_SAVE_ID}`

export interface DeveloperToolContextType extends UsePanelReturn {
  url: string
  setUrl: (url: string) => void
}

export const MAX_RESIZABLE_HEIGHT = 88
export const MIN_RESIZABLE_HEIGHT = 20
export const DEFAULT_RESIZABLE_HEIGHT = 40
export const FULLSCREEN = 100

export function DeveloperToolProvider({ children }: { children: ReactNode }) {
  const panel = usePanel({
    size: {
      open: DEFAULT_RESIZABLE_HEIGHT,
      closed: 0,
      maxResizableHeight: MAX_RESIZABLE_HEIGHT,
      minResizableHeight: MIN_RESIZABLE_HEIGHT,
      fullscreen: FULLSCREEN,
    },
  })

  const [url, setUrl] = useState('')

  return (
    <DeveloperToolContext.Provider
      value={{
        ...panel,
        url,
        setUrl,
      }}
    >
      {children}
    </DeveloperToolContext.Provider>
  )
}

export function useDeveloperTool(): DeveloperToolContextType {
  const context = useContext(DeveloperToolContext)
  const { currentUser } = useCurrentUser()

  const navigate = useNavigate()

  // We can copy/paste the URL of the devtools in the browser and it will open the devtools with the correct tab
  const checkParamsFromUrl = () => {
    const params = new URLSearchParams(window.location.search)
    const devtoolTab = params.get(DEVTOOL_TAB_PARAMS) ?? ''
    const decodedDevtoolTab = decodeURIComponent(devtoolTab)

    const isValidUser = !!currentUser

    if (decodedDevtoolTab && isValidUser) {
      navigate(decodedDevtoolTab)
      context?.openPanel()
    }

    // Remove the params from the URL
    params.delete(DEVTOOL_TAB_PARAMS)
    const url = `${window.location.pathname}`

    if (params?.toString()?.length > 0) {
      window.history.replaceState({}, '', `${url}?${params.toString()}`)
    } else {
      window.history.replaceState({}, '', url)
    }
  }

  useEffect(() => {
    // On mounted, check the params from the URL
    checkParamsFromUrl()

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Throw an error if the hook is used outside of the provider
  if (!context) {
    throw new Error('useDeveloperTool must be used within a DeveloperToolProvider')
  }

  return context
}
