export const INVOICE_LIST_FILTER_PREFIX = 'in'
export const CREDIT_NOTE_LIST_FILTER_PREFIX = 'cn'
export const CUSTOMER_LIST_FILTER_PREFIX = 'cu'
export const REVENUE_STREAMS_OVERVIEW_FILTER_PREFIX = 'rs'
