import {
  Quote,
  QuoteBackdatedBillingEnum,
  QuoteDefaultExecutionModeEnum,
  QuoteOrderTypeEnum,
  QuoteStatusEnum,
} from '../common/types'

export const QUOTE_DRAFT_FIXTURE: Quote = {
  __typename: 'Quote',
  id: 'quote-draft-001',
  organizationId: 'org-001',
  customer: { id: 'customer-001', name: 'Acme Corp', externalId: 'ext-acme-001' },
  templateId: 'template-001',
  number: 'QT-2026-0042',
  version: 1,
  status: QuoteStatusEnum.draft,
  orderType: QuoteOrderTypeEnum.subscriptionCreation,
  currency: 'EUR',
  description: 'Enterprise plan subscription for Acme Corp',
  validForDays: 30,
  billingItems: {
    planCode: 'enterprise',
    charges: [
      { billableMetricCode: 'api_calls', chargeModel: 'graduated' },
      { billableMetricCode: 'storage', chargeModel: 'standard' },
    ],
  },
  commercialTerms: {
    durationMonths: 12,
    startDate: '2026-05-01',
    paymentTerms: 'net_30',
    autoRenewal: true,
  },
  richTextContent:
    'Dear {customer.name},\n\nPlease find below our proposal for the Enterprise plan.',
  legalText: 'Standard terms and conditions apply. This quote is valid for {valid_for_days} days.',
  internalNotes: 'Discussed pricing with sales team on 2026-04-08.',
  contacts: [
    {
      id: 'qtct_contact-001',
      name: 'Jane Doe',
      email: 'jane.doe@acme.com',
      company: 'Acme Corp',
      role: 'CTO',
      position: 0,
    },
    {
      id: 'qtct_contact-002',
      name: 'John Smith',
      email: 'john.smith@acme.com',
      company: 'Acme Corp',
      role: 'VP Engineering',
      position: 1,
    },
  ],
  metadata: [{ key: 'salesforce_deal_id', value: 'SF-2026-1234' }],
  autoExecute: false,
  defaultExecutionMode: null,
  backdatedBilling: null,
  internalShareToken: 'sk_preview_abc123def456',
  approvedAt: null,
  voidedAt: null,
  voidedReason: null,
  createdAt: '2026-04-09T10:00:00Z',
  updatedAt: '2026-04-09T10:00:00Z',
  owners: [
    { id: 'user-001', name: 'Alice Martin', email: 'alice.martin@lago.dev' },
    { id: 'user-002', name: 'Bob Chen', email: 'bob.chen@lago.dev' },
  ],
}

export const QUOTE_APPROVED_FIXTURE: Quote = {
  __typename: 'Quote',
  id: 'quote-approved-001',
  organizationId: 'org-001',
  customer: { id: 'customer-002', name: 'Globex Inc', externalId: 'ext-globex-002' },
  templateId: 'template-001',
  number: 'QT-2026-0038',
  version: 2,
  status: QuoteStatusEnum.approved,
  orderType: QuoteOrderTypeEnum.subscriptionCreation,
  currency: 'USD',
  description: 'Pro plan subscription for Globex Inc',
  validForDays: 14,
  billingItems: {
    planCode: 'pro',
    charges: [{ billableMetricCode: 'seats', chargeModel: 'standard' }],
  },
  commercialTerms: {
    durationMonths: 6,
    startDate: '2026-04-15',
    paymentTerms: 'net_15',
    autoRenewal: false,
  },
  richTextContent: 'Dear Globex Inc,\n\nWe are pleased to offer the Pro plan.',
  legalText: 'Standard terms and conditions apply.',
  internalNotes: null,
  contacts: [
    {
      id: 'qtct_contact-003',
      name: 'Hank Scorpio',
      email: 'hank@globex.com',
      company: 'Globex Inc',
      role: 'CEO',
      position: 0,
    },
  ],
  metadata: null,
  autoExecute: true,
  defaultExecutionMode: QuoteDefaultExecutionModeEnum.executeInLago,
  backdatedBilling: null,
  internalShareToken: null,
  approvedAt: '2026-04-10T14:30:00Z',
  voidedAt: null,
  voidedReason: null,
  createdAt: '2026-04-01T09:00:00Z',
  updatedAt: '2026-04-10T14:30:00Z',
  owners: [{ id: 'user-003', name: 'Clara Davis', email: 'clara.davis@lago.dev' }],
}

export const QUOTE_VOIDED_FIXTURE: Quote = {
  __typename: 'Quote',
  id: 'quote-voided-001',
  organizationId: 'org-001',
  customer: { id: 'customer-003', name: 'Wayne Enterprises', externalId: 'ext-wayne-003' },
  templateId: null,
  number: 'QT-2026-0015',
  version: 1,
  status: QuoteStatusEnum.voided,
  orderType: QuoteOrderTypeEnum.oneOff,
  currency: 'EUR',
  description: 'One-off professional services engagement',
  validForDays: null,
  billingItems: {
    planCode: null,
    charges: [{ billableMetricCode: 'consulting_hours', chargeModel: 'standard' }],
  },
  commercialTerms: {
    durationMonths: null,
    startDate: '2026-03-01',
    paymentTerms: 'due_on_receipt',
    autoRenewal: false,
  },
  richTextContent: null,
  legalText: null,
  internalNotes: 'Customer decided to go with competitor.',
  contacts: [],
  metadata: null,
  autoExecute: false,
  defaultExecutionMode: null,
  backdatedBilling: null,
  internalShareToken: null,
  approvedAt: null,
  voidedAt: '2026-03-20T11:00:00Z',
  voidedReason: 'manual',
  createdAt: '2026-03-10T08:00:00Z',
  updatedAt: '2026-03-20T11:00:00Z',
  owners: [{ id: 'user-001', name: 'Alice Martin', email: 'alice.martin@lago.dev' }],
}

export const QUOTE_AMENDMENT_FIXTURE: Quote = {
  __typename: 'Quote',
  id: 'quote-amendment-001',
  organizationId: 'org-001',
  customer: { id: 'customer-001', name: 'Acme Corp', externalId: 'ext-acme-001' },
  templateId: 'template-002',
  number: 'QT-2026-0042',
  version: 2,
  status: QuoteStatusEnum.draft,
  orderType: QuoteOrderTypeEnum.subscriptionAmendment,
  currency: 'EUR',
  description: 'Upgrade Acme Corp from Pro to Enterprise',
  validForDays: 7,
  billingItems: {
    planCode: 'enterprise',
    charges: [
      { billableMetricCode: 'api_calls', chargeModel: 'graduated' },
      { billableMetricCode: 'storage', chargeModel: 'standard' },
      { billableMetricCode: 'seats', chargeModel: 'standard' },
    ],
  },
  commercialTerms: {
    durationMonths: 12,
    startDate: '2026-06-01',
    paymentTerms: 'net_30',
    autoRenewal: true,
  },
  richTextContent: 'Dear {customer.name},\n\nAs discussed, here is the amended subscription.',
  legalText: 'Amendment terms apply in addition to the original agreement.',
  internalNotes: 'Customer requested more seats and storage.',
  contacts: [
    {
      id: 'qtct_contact-001',
      name: 'Jane Doe',
      email: 'jane.doe@acme.com',
      company: 'Acme Corp',
      role: 'CTO',
      position: 0,
    },
  ],
  metadata: [
    { key: 'salesforce_deal_id', value: 'SF-2026-1234' },
    { key: 'original_quote_id', value: 'quote-draft-001' },
  ],
  autoExecute: true,
  defaultExecutionMode: QuoteDefaultExecutionModeEnum.executeInLago,
  backdatedBilling: QuoteBackdatedBillingEnum.generatePastInvoices,
  internalShareToken: 'sk_preview_xyz789ghi012',
  approvedAt: null,
  voidedAt: null,
  voidedReason: null,
  createdAt: '2026-04-09T15:00:00Z',
  updatedAt: '2026-04-09T15:00:00Z',
  owners: [
    { id: 'user-001', name: 'Alice Martin', email: 'alice.martin@lago.dev' },
    { id: 'user-002', name: 'Bob Chen', email: 'bob.chen@lago.dev' },
  ],
}

export const QUOTE_MINIMAL_FIXTURE: Quote = {
  __typename: 'Quote',
  id: 'quote-minimal-001',
  organizationId: 'org-001',
  customer: { id: 'customer-004', name: 'Initech', externalId: 'ext-initech-004' },
  templateId: null,
  number: 'QT-2026-0099',
  version: 1,
  status: QuoteStatusEnum.draft,
  orderType: QuoteOrderTypeEnum.oneOff,
  currency: null,
  description: null,
  validForDays: null,
  billingItems: null,
  commercialTerms: null,
  richTextContent: null,
  legalText: null,
  internalNotes: null,
  contacts: [],
  metadata: null,
  autoExecute: false,
  defaultExecutionMode: null,
  backdatedBilling: null,
  internalShareToken: 'sk_preview_min000',
  approvedAt: null,
  voidedAt: null,
  voidedReason: null,
  createdAt: '2026-04-09T12:00:00Z',
  updatedAt: '2026-04-09T12:00:00Z',
  owners: [],
}

export const ALL_QUOTES_FIXTURES = [
  QUOTE_DRAFT_FIXTURE,
  QUOTE_APPROVED_FIXTURE,
  QUOTE_VOIDED_FIXTURE,
  QUOTE_AMENDMENT_FIXTURE,
  QUOTE_MINIMAL_FIXTURE,
]
