name: Translation Check

on:
  pull_request:
    types: [opened, reopened, review_requested, ready_for_review, synchronize]

jobs:
  run-translation-check:
    name: Run Translation Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: yarn

      - name: Run Translation Check
        run: |
          yarn inspectTranslations
